---
- name: "Playbook to Add Key to EC2 Instances"
  hosts: controller_nodes,worker_nodes
  gather_facts: false
  vars:
    - status : "present"
    - key : "~/.ssh/{{ssh_rsa}}.pub"

  # pre_tasks:
  # - name: Wait for ssh/port 22
  #   wait_for:
  #     port: 22
  #     host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  #     search_regex: OpenSSH
  #     delay: 10
  #   connection: local

  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 900
  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ansible_user}}"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}"