- name: "Get terraform artifacts"
  hosts: localhost
  connection: local  
  tasks:
    - name: Get TF outputs
      shell: "terraform -chdir=../terraform/ output -json | jq 'with_entries(.value |= .value)'"
      register: tf_output

    - name: Read output
      set_fact:
        tf_output: "{{tf_output.stdout|default('utf8_general_ci')}}"

- import_playbook: build_nodes.yml
  tags:
    - build_nodes
- import_playbook: dashboard.yml



        
